# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171208_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='station',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
