# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171208_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metering',
            old_name='hum_out1',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='metering',
            old_name='bpress_out1',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='metering',
            old_name='temp_out1',
            new_name='temperature',
        ),
    ]
