# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171208_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metering',
            name='humidity',
            field=models.FloatField(blank=True, default=None, help_text='Outside relative humidity, in %.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='pressure',
            field=models.FloatField(blank=True, default=None, help_text='Outside absolute barometric pressure, in hPa.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temperature',
            field=models.FloatField(blank=True, default=None, help_text='Outside temperature, in C.', null=True),
        ),
    ]
