# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171208_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metering',
            name='hum_int_air1',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='hum_out2',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='hum_out3',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='pm01',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='rssi',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='temp_int_air1',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='temp_out2',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='temp_out3',
        ),
    ]
